const CONFIG = {
  gmailQuery: 'label:"Intake-Insurance Assignment" -label:"Intake-Processed" -label:intake-duplicate -label:"Intake-Pending Review" -label:"Intake-Error"',
  intakeLabel: 'Intake-Insurance Assignment',
  processedLabel: 'Intake-Processed',
  errorLabel: 'Intake-Error',
  duplicateLabel: 'intake-duplicate',
  needsReviewLabel: 'Intake-Pending Review',
  asbestosQuery: 'label:Asbestos -label:"Asbestos/Processed/Asbestos"',
  asbestosIntakeLabel: 'Asbestos',
  asbestosProcessedLabel: 'Asbestos/Processed/Asbestos',
  asbestosProcessedLabelLegacy: 'Processed-Asbestos',
  asbestosErrorLabel: 'Asbestos/Error',
  asbestosNeedsReviewLabel: 'Asbestos/Needs Review',
  asbestosPendingClaimFolderLabel: 'Asbestos/Pending Claim Folder',
  asbestosSubfolderName: 'Asbestos',
  // Temporary EMSL aliases route old EMSL calls to the new Asbestos labels during transition.
  emslQuery: 'label:Asbestos -label:"Asbestos/Processed/Asbestos"',
  emslIntakeLabel: 'Asbestos',
  emslProcessedLabel: 'Asbestos/Processed/Asbestos',
  emslErrorLabel: 'Asbestos/Error',
  emslNeedsReviewLabel: 'Asbestos/Needs Review',
  emslPendingClaimFolderLabel: 'Asbestos/Pending Claim Folder',
  itelQuery: 'label:Itel -label:"Itel/Processed/Itel"',
  itelIntakeLabel: 'Itel',
  itelProcessedLabel: 'Itel/Processed/Itel',
  itelProcessedLabelLegacy: 'Processed-Itel',
  itelErrorLabel: 'Itel/Error',
  itelNeedsReviewLabel: 'Itel/Needs Review',
  itelPendingClaimFolderLabel: 'Itel/Pending Claim Folder',
  itelSubfolderName: 'Itel',
  retryReadyLabel: 'Retry/Ready',
  retryInProgressLabel: 'Retry/In Progress',
  retryRecoveredLabel: 'Retry/Recovered',
  retryBlockedLabel: 'Retry/Blocked',
  retryLimitReachedLabel: 'Retry/Limit Reached',
  retryLogSheetName: 'Retry Log',
  maxRetryAttempts: 3,
  scheduledRetryTriggerHour: 7,
  automationName: 'Insurance Intake Automation',
  maxThreadsPerRun: 10,
  phase: '4F.2',
  dryRun: false,
  labelDryRun: false,
  claimFolderMapSpreadsheetId: '1kTRyZbPW1dZgkflH31s4MewuVHEl1ExQ7o3c6ad-btQ',
  claimFolderMapSheetName: 'Claim Folder Map',
  attachmentLogSheetName: 'Attachment Intake Log',
  claimFolderParentFolderId: '1r0A84zZGvUKA_0QFs1dwozbuteZt-DbL',
  createClaimFolders: true,
  calendar: {
    enabled: true,
    calendarId: '6aqe6hond86u044tgs868ouje8@group.calendar.google.com',
    startHour: 6,
    durationHours: 1,
    duplicateSearchDays: 30
  },
  todoist: {
    enabled: true,
    apiTokenProperty: 'TODOIST_API_TOKEN',
    projectIdProperty: 'TODOIST_PROJECT_ID',
    assigneeIdClarenceProperty: 'TODOIST_ASSIGNEE_ID_CLARENCE',
    sectionIdProperty: 'TODOIST_SECTION_ID',
    dueString: 'in 3 days',
    priority: 3
  },
  attachments: {
    detectionEnabled: true,
    loggingEnabled: true,
    labelingEnabled: false,
    duplicateCheckEnabled: true,
    manifestEnabled: true,
    manifestFileName: 'attachment-manifest.json',
    manifestSchemaVersion: 2,
    manifestReconciliationEnabled: true,
    manifestRepairEnabled: false,
    copyEnabled: true,
    copyVerificationEnabled: true,
    testMode: true,
    stabilizationEnabled: true,
    identityDuplicateCheckEnabled: true,
    filenameDuplicateCheckEnabled: true,
    logDuplicateCheckEnabled: true,
    recoveryModeEnabled: true,
    markUnreadOnRecoveryRequired: true,
    skipCopyIfManifestFileExists: true,
    skipCopyIfDriveFilenameExists: true,
    appendRecoveryLogRows: true,
    checksumEnabled: false,
    checksumMaxBytes: 10000000,
    maxAttachmentBytes: 25000000,
    retries: {
      enabled: true,
      maxCopyAttempts: 1,
      maxManifestAttempts: 1,
      maxSheetAttempts: 1,
      failFastOnDriveError: true
    },
    allowedMimeTypes: [
      'application/pdf',
      'image/jpeg',
      'image/png',
      'image/heic',
      'image/heif',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    ],
    reviewMimeTypes: [
      'application/zip',
      'application/x-zip-compressed',
      'application/octet-stream'
    ]
  }
};
